# spring:
#  application:
#    name: user-service
#  config:
#    import: "optional:configserver:http://localhost:9090"


spring:
  application:
    name: user-service
  cloud:
    config:
      uri: http://localhost:9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka